document.addEventListener("alpine:init",()=>{
    Alpine.data('transport',()=>{
        return{
            dayTime:'',
            results:'',
            dayTime_(){
                this.results=transportFee(this.dayTime);
            }
        }
    })
})